name: C/C++ CI

on:
  push:
    tags:
      - "v*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev \
            libpng-dev \
            libjpeg-dev

      - name: Build project
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: iv
          path: ./bin/iv
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/iv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
